[build]
  # This command (CI=false) fixes the "unused variable" build error
  command = "CI=false npm run build"
  
  # This is the folder for the final React app
  publish = "build"
  
  # This tells Netlify that our API folder is named "api"
  functions = "api"

# This part tells Netlify how to route API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
